### ISSUE TITLE
Emptying trash doesn't work under yet unknown circumstances

### ISSUE THREAD

**Issue by JMoVS** [openzfsonosx/zfs#469]
Ok, so I have checked that a little bit. I can empty the trash, get a progress bar and a nice paper crumpled sound. Then I kill Finder, and everything is back.

I can also ls into a `502` and a `503` folder in my dataset's .Trashes folder. Somehow it doesn't delete the stuff for real.

**Comment by JMoVS** [comment]
ok, running `ls -lrch` yielded the info that this trash hasn't been properly cleaned since February 7nth.

**Comment by ilovezfs** [comment]
I cannot reproduce this issue. Does it only affect ZFS on home directory?

**Comment by JMoVS** [comment]
very strange, will monitor, may be related to maybe changed user id

**Comment by JMoVS** [comment]
somehow I got into a state where there was only one correct folder (503) where I had emptied the trash but the finder didn't recognize the contents of one dataset as clean-worthy. After another killall Finder, it then noticed the files and now emptying it really did empty it and the files are gone from the .Trashes folder for real.

Sadly I cannot reliably reproduce it. What we can exclude as a reason are wrong user id folders as the specific dataset only has 503 (and no 502) and now correctly emptied the trash. I can only say that the dataset was mounted all along, that I previously killed the finder today, emptyed the trash afterwards, look in and saw stuff again and emptied it again.

I will report back if I notice something that gives me a reproducer

**Comment by JMoVS** [comment]
I have super strange behaviour on tape now. The files that are at some point seen are, according to the terminal, really in the .Trashes/503 folder of my Documents dataset.

Here it is:
[Finder WTF](https://cl.ly/fY0T)

**Comment by JMoVS** [comment]
so I logged out and logged back in again. I haven't *killed* Finder so to speak of. Immediatly after logging in, I can open the trash and see all files until they vanish after approx 5-15 seconds (as in the above linked video). So it seems highly unlikely to be related to me killing Finder.app

**Comment by JMoVS** [comment]
Was able to confirm the trashes issue on anothe machine, build of zfs there is: zfs: gaf351b2 spl: g12a3476

**Comment by lundman** [comment]
I had some luck re-creating this with:

```
$ cp modules/zfs/*.c /Volumes/BOOM  # add some files to delete later
$ rsync -ar /usr/ /Volumes/BOOM/usr1/  # mds has to be busy to trigger it, if idle, nothing happens
$ dtrace -n 'zfs_vfs_vget:entry { printf("ino %u: %s", arg1, execname); }' -n 'zfs_vfs_vget:return { printf("-> %u", arg1); }'
# Ensure mds is busy probing vget
```
Keep Trash window open.
Select; from one, to a handful of,  .C files and delete / move-to-trash. (Don't empty trash though)

Watch the Trash window sometime go empty.

First suspicion, mmap bug, triggered by two writers.

**Comment by JMoVS** [comment]
@lundman If you have a branch for me to test, I'm happy to compile and run it and see if it solves the problem for me.

**Comment by lundman** [comment]
Changing just 
```
diff --git a/module/zfs/zfs_vnops_osx.c b/module/zfs/zfs_vnops_osx.c
index 453f233..3c5103f 100644
--- a/module/zfs/zfs_vnops_osx.c
+++ b/module/zfs/zfs_vnops_osx.c
@@ -1861,7 +1861,7 @@ zfs_vnop_pagein(struct vnop_pagein_args *ap)

                dprintf("ZFS: pagein zeroing offset 0x%llx for 0x%llx bytes.\n",
                                newend, len - newend);
-               memset(&vaddr[newend], 0, len - newend);
+//             memset(&vaddr[newend], 0, len - newend);
                len = newend;
        }
        /*
```

Trash folder goes away, but comes back if you delete something else, which could suggest that mmap is indeed the problem.

I don't think we should zero anything in pagein. That doesn't sound right.

**Comment by JMoVS** [comment]
you mentioned in chat that it doesn't solve it, yet I didn't manage yet to test it. DO you want me to test it on my production system or should I wait for a proper branch?

**Comment by lundman** [comment]
Try chmoding the .Trashes/ folder to 1777 on the ZFS datasets.

**Comment by JMoVS** [comment]
doesn't help

**Comment by LATBauerdick** [comment]
I wanted to mention that I have a similar or possibly the same problem. I ended up with a folder in the trash that can't be gotten rid of (actually, it happened on two separate zpools on two of my macs).

Strangely even rm -rf of this folder does not work, as if there were an "invisible" file that rm can't see, but which prevents deletion of the directory where it's in.

$ sudo rm -rfv Pictures
rm: Pictures: Directory not empty

**Comment by JMoVS** [comment]
what is the output of ```ls -la``` for the Pictures folder? Also, have you tried running it as

`````
rm -rf Pictures/
```` 
(note the trailing slash)?

**Comment by LATBauerdick** [comment]
```
$ ls -la Pictures/
total 2
drwx------+ 3 bauerdic  staff  3 Jan 14 13:08 ./
drwxr-xr-x@ 3 bauerdic  staff  3 Feb 19 20:16 ../

$ sudo rm -rfv Pictures/
rm: Pictures/: Directory not empty

$ find Pictures/
Pictures/

```
it is really weird...

**Comment by lundman** [comment]
Certainly the test case I was doing, goes away:

```
# chmod 1777 /Volumes/BOOM/.Trashes/
# ls -lad /Volumes/BOOM/.Trashes/
drwxrwxrwt  3 root  wheel  3 Apr  7 14:58 /Volumes/BOOM/.Trashes/
```

It is curious why our `open()` on a directory with 1333 would differ to HFS though.

**Comment by ilovezfs** [comment]
try with https://openzfsonosx.org/wiki/File:O3x-1011-signed-spl-e755917-zfs-c4fe048.pkg
thanks

**Comment by LATBauerdick** [comment]
(assuming this was addressed to me...) installed this version, doesn't make any difference.

**Comment by JMoVS** [comment]
@lundman Ah, now it worked. Must have borked the chmod 1777...

**Comment by ilovezfs** [comment]
@LATBauerdick what's the output of
```
zfs list
```

**Comment by LATBauerdick** [comment]
@ilovezfs it's a long list (the affected ifs file system is zs/U)

```
NAME                          USED  AVAIL  REFER  MOUNTPOINT
h                            3.33T   189G   456K  none
h/BU                          349G   189G    96K  none
h/BU-save                     237G   189G    96K  none
h/BU-save/U                   237G   189G  39.5G  none
h/BU-save/U/Applications     2.01G   189G  2.01G  none
h/BU-save/U/Archive          37.1G   189G  34.1G  none
h/BU-save/U/Books            4.92G   189G  4.92G  none
h/BU/U                        349G   189G  41.3G  none
h/BU/U/Applications          2.43G   189G  2.39G  none
h/BU/U/Archive               65.5G   189G  33.5G  none
h/BU/U/Books                 4.95G   189G  4.94G  none
h/BU/U/DL                    5.89G   189G  5.89G  none
h/BU/U/Downloads              563M   189G   563M  none
h/BU/U/Dropbox               50.9G   189G  45.1G  none
h/BU/U/Music                  687M   189G   687M  none
h/BU/U/Pictures               150G   189G  7.49G  none
h/BU/U/Pictures/Aperture     71.2G   189G  57.4G  none
h/BU/U/Pictures/C1           29.7G   189G  28.5G  none
h/BU/U/Pictures/Lightroom    36.1G   189G  33.4G  none
h/BU/U/Pictures/ScreenSaver  4.92G   189G  4.87G  none
h/BU/U/Sync                   197M   189G   197M  none
h/P                          2.74T   189G   484K  /mnt/P
h/P/C1_Catalogs               211G   189G   211G  /mnt/P/C1_Catalogs
h/P/JPEGs                    54.6G   189G  54.6G  /mnt/P/JPEGs
h/P/O                        2.49T   189G   636K  /mnt/P/O
h/P/O/P1900s                  237G   189G   236G  /mnt/P/O/P1900s
h/P/O/P2000                  51.2G   189G  46.8G  /mnt/P/O/P2000
h/P/O/P2001                  30.5G   189G  28.2G  /mnt/P/O/P2001
h/P/O/P2002                  10.7G   189G  10.7G  /mnt/P/O/P2002
h/P/O/P2003                  12.2G   189G  10.0G  /mnt/P/O/P2003
h/P/O/P2004                  24.7G   189G  24.7G  /mnt/P/O/P2004
h/P/O/P2005                  29.0G   189G  28.9G  /mnt/P/O/P2005
h/P/O/P2006                  55.4G   189G  55.0G  /mnt/P/O/P2006
h/P/O/P2007                  70.9G   189G  70.8G  /mnt/P/O/P2007
h/P/O/P2008                  73.1G   189G  73.1G  /mnt/P/O/P2008
h/P/O/P2009                  72.6G   189G  72.6G  /mnt/P/O/P2009
h/P/O/P2010                   160G   189G   160G  /mnt/P/O/P2010
h/P/O/P2011                   174G   189G   174G  /mnt/P/O/P2011
h/P/O/P2012                   204G   189G   204G  /mnt/P/O/P2012
h/P/O/P2013                   276G   189G   276G  /mnt/P/O/P2013
h/P/O/P2014                   250G   189G   250G  /mnt/P/O/P2014
h/P/O/P2015                   338G   189G   335G  /mnt/P/O/P2015
h/P/O/P2016                  82.7G   189G  82.4G  /mnt/P/O/P2016
h/P/O/POthers                 106G   189G   106G  /mnt/P/O/POthers
h/P/O/Videos                  286G   189G   286G  /mnt/P/O/Videos
h/v                          10.9G   189G  10.9G  /Users/bauerdic/VirtualMachines
zs                            439G   290G    96K  none
zs/U                          438G   290G  25.4G  /Users/bauerdic
zs/U/Applications            2.64G   290G  2.27G  /Users/bauerdic/Applications
zs/U/Archive                 65.5G   290G  33.5G  none
zs/U/Books                   38.7G   290G  5.13G  /Users/bauerdic/Books
zs/U/Books-old               5.55G   290G  5.46G  /Users/bauerdic/Books-old
zs/U/Books/AllBooks          33.6G   290G  32.9G  /Users/bauerdic/Books/AllBooks
zs/U/DL                      5.89G   290G  5.89G  /Users/bauerdic/DL
zs/U/Downloads               1.62G   290G  1.43G  /Users/bauerdic/Downloads
zs/U/Dropbox                 93.6G   290G  75.2G  /Users/bauerdic/Dropbox
zs/U/Microsoft               52.6M   290G  52.6M  /Users/bauerdic/Microsoft
zs/U/Music                    818M   290G   780M  /Users/bauerdic/Music
zs/U/Pictures                 150G   290G  7.94G  /Users/bauerdic/Pictures
zs/U/Pictures/Aperture       71.2G   290G  57.5G  /Users/bauerdic/Pictures/Aperture
zs/U/Pictures/C1             29.7G   290G  28.5G  /Users/bauerdic/Pictures/C1
zs/U/Pictures/Lightroom      36.3G   290G  33.7G  /Users/bauerdic/Pictures/Lightroom
zs/U/Pictures/ScreenSaver    4.92G   290G  4.87G  /Users/bauerdic/Pictures/ScreenSaver
zs/U/Sync                     197M   290G   197M  /Users/bauerdic/Sync
```

**Comment by ilovezfs** [comment]
@LATBauerdick Did you try chmod'ing the .Trashes to 1777

**Comment by lundman** [comment]
@LATBauerdick 's problem is most likely a bad inode type bug, which you can patch around by setting zfs_recover. Should show long enough to `rm` it. Maybe

**Comment by lundman** [comment]
ok, so the `open` call goes wrong, has this stack:

```
  428/0x3372a7:  open("/Volumes/BOOM/.Trashes\0", 0x1100004, 0x10FC7F02C)		 = -1 Err#13

              libsystem_kernel.dylib`__open+0xa
              CoreServicesInternal`_GetDirectoryURLs(_CFURLEnumerator*)+0x17f
              CoreServicesInternal`_URLEnumeratorGetNextURL+0xa7
              DesktopServicesPriv`TFSIterator::NextRaw(TCountedPtr<TFSInfo>&)+0x2f
              DesktopServicesPriv`TFSIterator::Next(TCountedPtr<TFSInfo>&)+0x1f
              DesktopServicesPriv`TFSInfoSynchronizer::FetchChildren()+0xea
              DesktopServicesPriv`TNode::SynchronizeChildren(NodeRequestOptions, TNodeEventPtrs&)+0x28a
              DesktopServicesPriv`TNode::HandleSync(NodeRequestOptions, TNodeEventPtrs&)+0xa02
              DesktopServicesPriv`TNode::HandleSync(NodeRequestOptions)+0x21
              DesktopServicesPriv`TNode::HandleSync(TCountedPtr<TNodeTask> const&, TNodePtr const&)+0x2a
              DesktopServicesPriv`TNode::HandleNodeRequest(TCountedPtr<TNodeTask> const&)+0xc7
              DesktopServicesPriv`___ZN17TVolumeSyncThread19PostNodeTaskRequestEP9TNodeTask_block_invoke_2+0x33
              DesktopServicesPriv`ExceptionSafeBlock(void () block_pointer)+0xc
              DesktopServicesPriv`___ZN17TVolumeSyncThread19PostNodeTaskRequestEP9TNodeTask_block_invoke+0x50
              libdispatch.dylib`_dispatch_call_block_and_release+0xc
              libdispatch.dylib`_dispatch_client_callout+0x8
```

It is interesting to note that HFS never tries to call `open` so it has decided something earlier, but the calling stack is similar, ie inside `URLEnumeratorGetNextURL`.

**Comment by lundman** [comment]
It would appear that RE on `CoreServicesInternal` show that `GetDirectoryURLs` will eventually use `ftsopen` which will call `getattrlistbulk` if available. If not, it will fall back to regular directory listing and getattrlist. Most probably, once we implement `vnop_getattrlistbulk` it should work as expected.

**Comment by ilovezfs** [comment]
Fixed by the great and mighty @lundman https://github.com/openzfsonosx/zfs/commit/6af8882ff117884eca9c82e808226ae89eca3ca7

**Comment by ylluminate** [comment]
@lundman interestingly I'm having this issue. I just updated to the beta build from last month and still having the same thing.  First the folder started off in the .Trashes on a ZFS volume. I then thought I'd mv it down as root to see what would happen and also rename it. Nothing there helped. I tried `chmod 1777` and likewise it would still not rm.
```
su
root $ cd /Volumes/tank/
root $ rm -fr rmme/test/
rm: rmme/test/: Directory not empty
chmod -R 1777 rmme
rm -fr rmme/
rm: rmme//test: Directory not empty
rm: rmme/: Directory not empty
ls -lad rmme/
drwxrwxrwt+ 3 username  staff  3 May 12 18:04 rmme/
```
